version: '3.3'
services:
    spring-boot:
        build:
            context: .docker/
            dockerfile: Dockerfile
        volumes:
            - './:/app'
        working_dir: /app
        command:
            - ./wait-for-it.sh
            - 'redis:6379'
            - '--'
            - sh
            - run.sh
        depends_on:
            - redis
        links:
            - redis
        ports:
            - '8080:8080'
    redis:
        image: redis
        expose:
            - 6379
